
const data = [
  {
    "Id": "1",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "2",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "3",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "4",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "5",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "6",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "7",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "8",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "9",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "10",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "11",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "12",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "13",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "14",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "15",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "16",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "17",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "18",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "19",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "20",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "21",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "22",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "23",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "24",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "25",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "26",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "27",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "28",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "29",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "30",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "31",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "32",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "33",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "34",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "35",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "36",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "37",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "38",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  },
  {
    "Id": "39",
    "Jobrole": "UI/UX Designer",
    "JobType": "Fulltime",
    "Openings": "24",
    "Location": "Noida",
    "Exp": "01-03",
    "Pointsrequired": "200-411",
    "Invitessend": "24",
    "Accepted": "56",
    "Creationdates": "24-02-2023",
  }
]

export default data;